import { StyleSheet } from 'react-native';

export const wordBankStyles = StyleSheet.create({
  answerTray: {
    minHeight: 92,
    borderRadius: 12,
    borderWidth: 1.5,
    borderBottomWidth: 2,
    borderColor: '#E5E5E5',
    borderBottomColor: '#D1D5DB',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 14,
    marginBottom: 4,
    position: 'relative',
  },
  answerTrayCompact: {
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 8,
    marginBottom: 4,
    borderBottomWidth: 2,
  },
  answerTrayIncorrect: {
    backgroundColor: '#FFF1F3',
    borderColor: '#F06A7F',
    borderBottomColor: '#D94E64',
  },
  answerPlaceholderText: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    opacity: 0.38,
    paddingVertical: 10,
    width: '100%',
  },
  selectedWordsRow: {
    minHeight: 54,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingTop: 4,
    paddingBottom: 5,
  },
  selectedWordsRowCompact: {
    gap: 5,
    paddingTop: 2,
    paddingBottom: 3,
  },
  selectedWordsRowWithClear: {
    paddingLeft: 36,
    paddingRight: 36,
  },
  clearAnswerButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1.25,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 7,
    top: 7,
    width: 28,
    zIndex: 5,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
  },
  dividerLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  wordBankPanel: {
    borderRadius: 12,
    backgroundColor: '#F7F7F7',
    borderWidth: 1.25,
    borderBottomWidth: 2,
    borderColor: '#E5E5E5',
    padding: 18,
    marginBottom: 12,
  },
  wordBankPanelCompact: {
    marginBottom: 8,
  },
  wordBank: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  wordChip: {
    paddingVertical: 11,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: '#E5E5E5',
    borderBottomColor: '#D1D5DB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  wordChipCompact: {
    borderBottomWidth: 3,
  },
  wordChipDesktopWeb: {
    borderBottomWidth: 3,
  },
  wordChipText: {
    color: '#4B4B4B',
    fontSize: 16,
    fontWeight: '700',
  },
  wordChipTextCompact: {
    fontSize: 15,
  },
  wordChipTextDesktopWeb: {
    fontSize: 17,
  },
  selectedWordChip: {
    paddingVertical: 11,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: '#1A8FD8',
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: '#78CBFF',
    borderBottomColor: '#1277B3',
    alignSelf: 'flex-start',
  },
  selectedWordDragWrap: {
    alignSelf: 'flex-start',
  },
  siblingChipDuringDrag: {
    opacity: 0.65,
  },
  dropTargetChip: {
    opacity: 0.42,
    borderColor: '#4A9FF5',
    borderWidth: 2.5,
    borderBottomColor: '#2A7FD5',
    borderBottomWidth: 2.5,
  },
  selectedWordChipCompact: {
    paddingVertical: 8,
    paddingHorizontal: 11,
    borderBottomWidth: 3,
  },
  selectedWordChipDesktopWeb: {
    paddingVertical: 11,
    paddingHorizontal: 16,
  },
  selectedWordChipText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  selectedWordChipTextCompact: {
    fontSize: 15,
  },
  selectedWordChipTextDesktopWeb: {
    fontSize: 17,
  },
  disabledWordChip: {
    opacity: 0.3,
  },
  disabledWordChipText: {
    color: '#6f8798',
  },
  checkAnswerButton: {
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: '#1F7AD1',
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: '#1F7AD1',
    borderBottomColor: '#155B9F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkAnswerButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  checkAnswerButtonCompact: {
    minHeight: 46,
    borderBottomWidth: 3,
  },
  checkAnswerButtonDesktopWeb: {
    minHeight: 58,
  },
  disabledCheckAnswerButton: {
    opacity: 0.45,
  },
  checkAnswerButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  exerciseErrorText: {
    color: '#A12A3D',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  incorrectOption: {
    backgroundColor: '#FFE8EC',
    borderColor: '#F06A7F',
    borderBottomColor: '#D94E64',
  },
});
