const ArticlesGrammar = {
  id: '40',
  title: 'Les articles',
  description: 'Definite and indefinite articles: a, an, the and when to omit them',
  imageUrl: 'https://wretggbpaejzjdilemit.supabase.co/storage/v1/object/public/lesson-images/15274719ab/les-articles.webp',
  textContent: {
    cards: [
      {
        eyebrow: 'The, a, an',
        paragraph: "J'utilise un article devant un nom. Je montre si je parle de quelque chose de précis ou de général.",
        tip: '**The** (article défini) = un nom précis ou connu. **A / an** (article indéfini) = un nom parmi d’autres. On utilise **an** devant un son voyelle.',
        examples: [
          { en: '**The** book on the table is mine.', fr: 'Le livre sur la table est à moi.' },
          { en: 'I like **the** cake you made.', fr: 'J’aime le gâteau que tu as fait.' },
          { en: 'I saw **a** dog.', fr: 'J’ai vu un chien.' },
          { en: 'She eats **an** orange.', fr: 'Elle mange une orange.' },
        ],
      },
      {
        eyebrow: 'Pas d’article',
        paragraph: 'Pas d’article devant un nom en général ou au pluriel.',
        examples: [
          { en: '**Dogs** are friendly.', fr: 'Les chiens sont gentils.' },
          { en: 'I like **music**.', fr: 'J’aime la musique (en général).' },
        ],
      },
    ],
  },

  translateExercises: [
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: "J’ai un chien.",
      answer: 'I have a dog.',
      wordBank: ['I', 'have', 'a', 'an', 'the', 'dog'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Elle mange une pomme.',
      answer: 'She eats an apple.',
      wordBank: ['She', 'eats', 'a', 'an', 'the', 'apple'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Je lis un livre.',
      answer: 'I read a book.',
      wordBank: ['I', 'read', 'a', 'an', 'the', 'book'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Il voit un oiseau.',
      answer: 'He sees a bird.',
      wordBank: ['He', 'sees', 'a', 'an', 'the', 'bird'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Nous avons une maison.',
      answer: 'We have a house.',
      wordBank: ['We', 'have', 'a', 'an', 'the', 'house'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Tu as une idée.',
      answer: 'You have an idea.',
      wordBank: ['You', 'have', 'a', 'an', 'the', 'idea'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le chat dort.',
      answer: 'The cat sleeps.',
      wordBank: ['The', 'a', 'cat', 'sleeps'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le soleil brille.',
      answer: 'The sun shines.',
      wordBank: ['The', 'a', 'sun', 'shines'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'La porte est ouverte.',
      answer: 'The door is open.',
      wordBank: ['The', 'a', 'door', 'is', 'open'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le café est chaud.',
      answer: 'The coffee is hot.',
      wordBank: ['The', 'a', 'coffee', 'is', 'hot'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le téléphone sonne.',
      answer: 'The phone rings.',
      wordBank: ['The', 'a', 'phone', 'rings'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'La musique est belle.',
      answer: 'The music is beautiful.',
      wordBank: ['The', 'a', 'music', 'is', 'beautiful'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le chien a un jouet.',
      answer: 'The dog has a toy.',
      wordBank: ['The', 'dog', 'has', 'a', 'an', 'the', 'toy'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le chat mange une souris.',
      answer: 'The cat eats a mouse.',
      wordBank: ['The', 'cat', 'eats', 'a', 'an', 'the', 'mouse'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'La fille a un vélo.',
      answer: 'The girl has a bike.',
      wordBank: ['The', 'girl', 'has', 'a', 'an', 'the', 'bike'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le garçon lit un livre.',
      answer: 'The boy reads a book.',
      wordBank: ['The', 'boy', 'reads', 'a', 'an', 'the', 'book'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le professeur a une classe.',
      answer: 'The teacher has a class.',
      wordBank: ['The', 'teacher', 'has', 'a', 'an', 'the', 'class'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'La femme boit un café.',
      answer: 'The woman drinks a coffee.',
      wordBank: ['The', 'woman', 'drinks', 'a', 'an', 'the', 'coffee'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: 'Le bébé a un jouet.',
      answer: 'The baby has a toy.',
      wordBank: ['The', 'baby', 'has', 'a', 'an', 'the', 'toy'],
    },
    {
      type: 'translate',
      question: 'Translate into English.',
      prompt: "L’homme mange une pomme.",
      answer: 'The man eats an apple.',
      wordBank: ['The', 'man', 'eats', 'a', 'an', 'the', 'apple'],
    },
  ],

  exercises: [
    { question: 'I have ___ dog.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'She eats ___ apple.', answer: 'an', options: ['a', 'an', 'the'] },
    { question: 'This is ___ book.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'He has ___ orange.', answer: 'an', options: ['a', 'an', 'the'] },
    { question: 'Open ___ door, please.', answer: 'the', options: ['a', 'an', 'the'] },
    { question: 'I see ___ bird in the tree.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: '___ cat is on the chair.', answer: 'The', options: ['A', 'An', 'The'] },
    { question: 'Do you want ___ egg?', answer: 'an', options: ['a', 'an', 'the'] },
    { question: 'I need ___ pen.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'Put ___ cup on the table.', answer: 'the', options: ['a', 'an', 'the'] },
    { question: 'There is ___ bag under the desk.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'She has ___ umbrella.', answer: 'an', options: ['a', 'an', 'the'] },
    { question: 'I like ___ dogs.', answer: 'no article', options: ['a', 'the', 'no article'] },
    { question: 'We play ___ football after school.', answer: 'no article', options: ['a', 'the', 'no article'] },
    { question: 'He drinks ___ water.', answer: 'no article', options: ['a', 'the', 'no article'] },
    { question: 'The boy has ___ toy.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'The girl reads ___ book.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'Give me ___ apple on the plate.', answer: 'the', options: ['a', 'an', 'the'] },
    { question: 'Turn on ___ light.', answer: 'the', options: ['a', 'an', 'the'] },
    { question: 'They have ___ house.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'This is ___ old chair.', answer: 'an', options: ['a', 'an', 'the'] },
    { question: 'I want ___ sandwich.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'She opens ___ window.', answer: 'the', options: ['a', 'an', 'the'] },
    { question: 'We need ___ box.', answer: 'a', options: ['a', 'an', 'the'] },
    { question: 'He likes ___ music.', answer: 'no article', options: ['a', 'the', 'no article'] },
  ],
};

export default ArticlesGrammar;
