const FrequencyGrammar = {
  id: '37',
  title: 'Adverbes de fréquence',
  description: 'Learn how to use frequency adverbs',
  category: 'Adverbes',
  imageUrl: 'https://i.ibb.co/FLZ8jY8C/fr-quence-batons.png',
  exercises: [
  { "question": "I always drink water in the morning.", "answer": true, "explanation": "'Always' goes before the main verb." },
  { "question": "She goes usually to the park on Sundays.", "answer": false, "explanation": "Incorrect: 'usually' should be before the main verb. Correct: 'She usually goes to the park'." },
  { "question": "They often play football after school.", "answer": true, "explanation": "'Often' is correctly placed before the main verb." },
  { "question": "We eats sometimes breakfast late.", "answer": false, "explanation": "Incorrect: adverb placement is wrong and verb should be base form. Correct: 'We sometimes eat breakfast late'." },
  { "question": "He usually studies in the library.", "answer": true, "explanation": "'Usually' comes before the main verb." },
  { "question": "I go always to bed at 10 pm.", "answer": false, "explanation": "Incorrect: 'always' should come before the main verb. Correct: 'I always go to bed'." },
  { "question": "You always arrive on time for class.", "answer": true, "explanation": "'Always' is correctly placed before the main verb." },
  { "question": "She rarely eats chocolate.", "answer": true, "explanation": "'Rarely' is correctly placed before the main verb." },
  { "question": "They eats never meat.", "answer": false, "explanation": "Incorrect: adverb 'never' should come before the main verb. Correct: 'They never eat meat'." },
  { "question": "We watch often movies on Friday.", "answer": false, "explanation": "Incorrect: 'often' should come before the main verb. Correct: 'We often watch movies'." },
  { "question": "He usually goes to bed early.", "answer": true, "explanation": "'Usually' is correctly placed before the main verb." },
  { "question": "I am always happy.", "answer": true, "explanation": "With 'to be', adverb comes after the verb. Correct." },
  { "question": "They are sometimes late for class.", "answer": true, "explanation": "With 'to be', adverb goes after the verb." },
  { "question": "She is never tired in the morning.", "answer": true, "explanation": "'Never' correctly placed after 'is'." },
  { "question": "We are usually enjoying our lunch at noon.", "answer": true, "explanation": "Adverb is correctly placed after 'are' for continuous action." },
  { "question": "I am often go to the gym.", "answer": false, "explanation": "Incorrect: after 'am' use '-ing' form. Correct: 'I am often going to the gym'." },
  { "question": "He has always finished his homework on time.", "answer": true, "explanation": "Adverb goes between 'has' and past participle." },
  { "question": "She has finished always her work before class.", "answer": false, "explanation": "Incorrect: 'always' should go between 'has' and past participle. Correct: 'She has always finished her work'." },
  { "question": "They have never visited that museum.", "answer": true, "explanation": "Adverb 'never' goes between 'have' and past participle." },
  { "question": "We have visited often that museum.", "answer": false, "explanation": "Incorrect: adverb should go between 'have' and past participle. Correct: 'We have often visited that museum'." },
  { "question": "I sometimes read books in the evening.", "answer": true, "explanation": "'Sometimes' correctly before the main verb." },
  { "question": "You plays often football on weekends.", "answer": false, "explanation": "Incorrect: adverb placement and verb form. Correct: 'You often play football'." },
  { "question": "He is always polite to strangers.", "answer": true, "explanation": "With 'to be', adverb after the verb is correct." },
  { "question": "They rarely are late to meetings.", "answer": false, "explanation": "Incorrect: with 'to be', adverb comes after the verb. Correct: 'They are rarely late'." },
  { "question": "We always eat breakfast together.", "answer": true, "explanation": "Adverb correctly placed before the main verb." },
  { "question": "I am never happy when it rains.", "answer": true, "explanation": "Adverb after 'am' is correct." },
  { "question": "She often is tired after work.", "answer": false, "explanation": "Incorrect: with 'to be', adverb should follow the verb. Correct: 'She is often tired'." },
  { "question": "They sometimes go to the park on Sundays.", "answer": true, "explanation": "'Sometimes' correctly before the main verb." },
  { "question": "We are always excited for holidays.", "answer": true, "explanation": "Adverb after 'are' is correct for state verbs." },
  { "question": "He is rarely forgetful.", "answer": true, "explanation": "Adverb after 'is' is correct." }
]
};

export default FrequencyGrammar;