const HadToWasAllowedToGrammar = {
  id: '34',
  title: 'Had to / Was Allowed To',
  description: 'Practice past obligations and permissions using had to and was allowed to',
  imageUrl: 'https://i.ibb.co/bM0X7zyC/Had-to-Was-Allowed-to.png',
  exercises: [
  { "question": "The students had to submit their projects on time.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The children was allowed to eat ice cream after lunch.", "answer": false, "explanation": "Incorrect: 'children' is plural, so it should be 'were allowed to'." },
  { "question": "The employees had to attend the meeting yesterday.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The teacher was allowed to to take a break.", "answer": false, "explanation": "Incorrect: 'was allowed to' should not be followed by 'to'. Correct: 'was allowed to take'." },
  { "question": "The kids had to clean the classroom after art class.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The pets were allowed to plays in the garden.", "answer": false, "explanation": "Incorrect: after 'were allowed to' use base verb. Correct: 'were allowed to play'." },
  { "question": "The tourists had to buy tickets before entering the museum.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The visitors was allowed to take photos inside the exhibition.", "answer": false, "explanation": "Incorrect: 'visitors' is plural, so use 'were allowed to'." },
  { "question": "The team had to practice every day last week.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The children were allowed to watched cartoons after homework.", "answer": false, "explanation": "Incorrect: after 'were allowed to' use base verb. Correct: 'were allowed to watch'." },
  { "question": "The players had to wear helmets during the match.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The students was allowed to leave early on Friday.", "answer": false, "explanation": "Incorrect: 'students' is plural, so it should be 'were allowed to'." },
  { "question": "The chef had to prepare all dishes before noon.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "I had to finish my homework before dinner.", "answer": true, "explanation": "'Had to' + base verb expresses past obligation." },
  { "question": "You was allowed to play outside yesterday.", "answer": false, "explanation": "Incorrect: 'you' with past permission uses 'were allowed to'. Correct: 'You were allowed to play'." },
  { "question": "He had to wake up early for the meeting.", "answer": true, "explanation": "'Had to' + base verb expresses past obligation." },
  { "question": "She were allowed to go to the cinema.", "answer": false, "explanation": "Incorrect: 'She' takes 'was allowed to', not 'were allowed to'." },
  { "question": "We had to clean the classroom after the lesson.", "answer": true, "explanation": "'Had to' + base verb expresses past obligation." },
  { "question": "They was allowed to eat ice cream after lunch.", "answer": false, "explanation": "Incorrect: 'They' takes 'were allowed to', not 'was allowed to'." },
  { "question": "It had to be repaired before the exhibition.", "answer": true, "explanation": "'Had to' + base verb expresses past necessity." },
  { "question": "I was allowed to to use the library computer.", "answer": false, "explanation": "Incorrect: 'was allowed to' should not be followed by 'to'. Correct: 'was allowed to use'." },
  { "question": "You had to wear a uniform at school yesterday.", "answer": true, "explanation": "'Had to' + base verb expresses past obligation." },
  { "question": "She were allowed to taking a break during class.", "answer": false, "explanation": "Incorrect: after 'was/were allowed to' use base verb. Correct: 'was allowed to take'." },
  { "question": "We had to submit our projects before the deadline.", "answer": true, "explanation": "'Had to' + base verb expresses past obligation." },
  { "question": "The athletes had to train in the morning.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The employees was allowed to choose their own schedule.", "answer": false, "explanation": "Incorrect: 'employees' is plural, so use 'were allowed to'." },
  { "question": "The children had to wear uniforms at school.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The tourists were allowed to took pictures on the bridge.", "answer": false, "explanation": "Incorrect: after 'were allowed to' use base verb. Correct: 'were allowed to take'." },
  { "question": "The drivers had to stop at the red light yesterday.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The students were allowed to talking during lunch.", "answer": false, "explanation": "Incorrect: after 'were allowed to' use base verb. Correct: 'were allowed to talk'." },
  { "question": "The children had to finish their homework before playing.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The staff were allowed to to leave early on Friday.", "answer": false, "explanation": "Incorrect: 'were allowed to' should not be followed by 'to'. Correct: 'were allowed to leave'." },
  { "question": "The students had to attend the assembly yesterday.", "answer": true, "explanation": "'Had to' expresses past obligation." },
  { "question": "The children were allowed to runs in the park.", "answer": false, "explanation": "Incorrect: after 'were allowed to' use base verb. Correct: 'were allowed to run'." }
]
};

export default HadToWasAllowedToGrammar;