const PassivePresGrammar = {
  id: '18',
  title: 'Voix passive présent',
  description: 'Learn how to use the passive voice in present tense',
  category: 'Voix passive',
  imageUrl: 'https://i.ibb.co/dsgdyzH9/La-voix-passive-au-pr-sent.png',
  exercises: [
  { "question": "The letter ___ (write) every day.", "answer": "is written", "options": ["is written", "are written"] },
  { "question": "The dishes ___ (wash) after every meal.", "answer": "are washed", "options": ["is washed", "are washed"] },
  { "question": "He ___ (remind) about his homework.", "answer": "is reminded", "options": ["is reminded", "are reminded"] },
  { "question": "She ___ (give) a lot of attention by her teacher.", "answer": "is given", "options": ["is given", "are given"] },
  { "question": "We ___ (inform) of any schedule changes.", "answer": "are informed", "options": ["is informed", "are informed"] },
  { "question": "The students ___ (ask) many questions in class.", "answer": "are asked", "options": ["is asked", "are asked"] },
  { "question": "It ___ (fix) quickly by the technician.", "answer": "is fixed", "options": ["is fixed", "are fixed"] },
  { "question": "I ___ (teach) new grammar rules every week.", "answer": "am taught", "options": ["am taught", "is taught", "are taught"] },
  { "question": "You ___ (show) the new office every morning.", "answer": "are shown", "options": ["is shown", "are shown"] },
  { "question": "The team ___ (invite) to participate in competitions.", "answer": "is invited", "options": ["is invited", "are invited"] },
  { "question": "She ___ (help) with her tasks every day.", "answer": "is helped", "options": ["is helped", "are helped"] },
  { "question": "We ___ (ask) to complete the form every week.", "answer": "are asked", "options": ["is asked", "are asked"] },
  { "question": "The documents ___ (check) carefully by the assistant.", "answer": "are checked", "options": ["is checked", "are checked"] },
  { "question": "It ___ (repair) immediately when broken.", "answer": "is repaired", "options": ["is repaired", "are repaired"] },
  { "question": "The emails ___ (send) every morning.", "answer": "are sent", "options": ["is sent", "are sent"] },
  { "question": "I ___ (remind) to submit my homework every day.", "answer": "am reminded", "options": ["am reminded", "is reminded", "are reminded"] },
  { "question": "You ___ (invite) to attend meetings every week.", "answer": "are invited", "options": ["is invited", "are invited"] },
  { "question": "The windows ___ (clean) regularly.", "answer": "are cleaned", "options": ["is cleaned", "are cleaned"] },
  { "question": "He ___ (inform) about the rules by his manager.", "answer": "is informed", "options": ["is informed", "are informed"] },
  { "question": "She ___ (remind) about the deadlines.", "answer": "is reminded", "options": ["is reminded", "are reminded"] },
  { "question": "The packages ___ (deliver) every afternoon.", "answer": "are delivered", "options": ["is delivered", "are delivered"] },
  { "question": "We ___ (teach) new vocabulary every lesson.", "answer": "are taught", "options": ["is taught", "are taught"] },
  { "question": "The letters ___ (send) to clients every week.", "answer": "are sent", "options": ["is sent", "are sent"] },
  { "question": "I ___ (show) new procedures by my manager.", "answer": "am shown", "options": ["am shown", "is shown", "are shown"] },
  { "question": "The students ___ (help) by the assistants in the library.", "answer": "are helped", "options": ["is helped", "are helped"] },
  { "question": "It ___ (check) before every presentation.", "answer": "is checked", "options": ["is checked", "are checked"] },
  { "question": "The homework ___ (collect) at the end of each lesson.", "answer": "is collected", "options": ["is collected", "are collected"] },
  { "question": "You ___ (remind) about meetings every Monday.", "answer": "are reminded", "options": ["is reminded", "are reminded"] },
  { "question": "The results ___ (announce) at the end of the week.", "answer": "are announced", "options": ["is announced", "are announced"] },
  { "question": "She ___ (show) the new program every semester.", "answer": "is shown", "options": ["is shown", "are shown"] }
]
};

export default PassivePresGrammar;