const PassivePastGrammar = {
  id: '38',
  title: 'Voix passive passée',
  description: 'Learn how to use the passive voice in past tense',
  category: 'Voix passive',
  imageUrl: 'https://i.ibb.co/jPhFF9Rk/La-voix-passive-au-pass.png',
  exercises: [
  { "question": "The letter ___ (write) yesterday.", "answer": "was written", "options": ["is written", "was written", "are written", "were written"] },
  { "question": "The dishes ___ (wash) after dinner.", "answer": "were washed", "options": ["is washed", "was washed", "are washed", "were washed"] },
  { "question": "The movie ___ (direct) by Spielberg.", "answer": "was directed", "options": ["is directed", "was directed", "are directed", "were directed"] },
  { "question": "The books ___ (sell) at auction.", "answer": "were sold", "options": ["is sold", "was sold", "are sold", "were sold"] },
  { "question": "The car ___ (fix) last week.", "answer": "was fixed", "options": ["is fixed", "was fixed", "are fixed", "were fixed"] },
  { "question": "The house ___ (build) in 1990.", "answer": "was built", "options": ["is built", "was built", "are built", "were built"] },
  { "question": "The paintings ___ (display) in the museum.", "answer": "were displayed", "options": ["is displayed", "was displayed", "are displayed", "were displayed"] },
  { "question": "The game ___ (cancel) due to rain.", "answer": "was canceled", "options": ["is canceled", "was canceled", "are canceled", "were canceled"] },
  { "question": "The documents ___ (sign) by the manager.", "answer": "were signed", "options": ["is signed", "was signed", "are signed", "were signed"] },
  { "question": "The window ___ (break) by the storm.", "answer": "was broken", "options": ["is broken", "was broken", "are broken", "were broken"] },
  { "question": "The flowers ___ (plant) in spring.", "answer": "were planted", "options": ["is planted", "was planted", "are planted", "were planted"] },
  { "question": "The story ___ (publish) last month.", "answer": "was published", "options": ["is published", "was published", "are published", "were published"] },
  { "question": "The rules ___ (explain) to everyone.", "answer": "were explained", "options": ["is explained", "was explained", "are explained", "were explained"] },
 { "question": "I ___ (call) by my teacher yesterday.", "answer": "was called", "options": ["is called", "was called", "are called", "were called"] },
  { "question": "You ___ (invite) to the party last week.", "answer": "were invited", "options": ["is invited", "was invited", "are invited", "were invited"] },
  { "question": "He ___ (remind) about the meeting.", "answer": "was reminded", "options": ["is reminded", "was reminded", "are reminded", "were reminded"] },
  { "question": "She ___ (give) a gift on her birthday.", "answer": "was given", "options": ["is given", "was given", "are given", "were given"] },
  { "question": "We ___ (inform) about the schedule changes.", "answer": "were informed", "options": ["is informed", "was informed", "are informed", "were informed"] },
  { "question": "They ___ (ask) to leave the room.", "answer": "were asked", "options": ["is asked", "was asked", "are asked", "were asked"] },
  { "question": "It ___ (fix) by the mechanic yesterday.", "answer": "was fixed", "options": ["is fixed", "was fixed", "are fixed", "were fixed"] },
  { "question": "I ___ (teach) new grammar rules last week.", "answer": "was taught", "options": ["is taught", "was taught", "are taught", "were taught"] },
  { "question": "You ___ (show) the new office yesterday.", "answer": "were shown", "options": ["is shown", "was shown", "are shown", "were shown"] },
  { "question": "He ___ (invite) to join the team.", "answer": "was invited", "options": ["is invited", "was invited", "are invited", "were invited"] },
  { "question": "She ___ (help) with the project.", "answer": "was helped", "options": ["is helped", "was helped", "are helped", "were helped"] },
  { "question": "We ___ (ask) to complete the form.", "answer": "were asked", "options": ["is asked", "was asked", "are asked", "were asked"] },
  { "question": "They ___ (inform) about the decision.", "answer": "were informed", "options": ["is informed", "was informed", "are informed", "were informed"] },
  { "question": "It ___ (repair) last week.", "answer": "was repaired", "options": ["is repaired", "was repaired", "are repaired", "were repaired"] },
  { "question": "The awards ___ (give) last month.", "answer": "were given", "options": ["is given", "was given", "are given", "were given"] },
  { "question": "The homework ___ (finish) by the students before class.", "answer": "was finished", "options": ["is finished", "was finished", "are finished", "were finished"] },
  { "question": "The emails ___ (check) by the assistant yesterday.", "answer": "were checked", "options": ["is checked", "was checked", "are checked", "were checked"] },
  { "question": "The lights ___ (turn off) after the meeting.", "answer": "were turned off", "options": ["is turned off", "was turned off", "are turned off", "were turned off"] },
  { "question": "The message ___ (send) to all employees.", "answer": "was sent", "options": ["is sent", "was sent", "are sent", "were sent"] },
  { "question": "The room ___ (decorate) for the party.", "answer": "was decorated", "options": ["is decorated", "was decorated", "are decorated", "were decorated"] }
]
};

export default PassivePastGrammar;