const PresentSimpleGrammar = {
  id: '1',
  title: 'Present Simple',
  description: 'Learn how to use the present simple tense',
  imageUrl: 'https://i.ibb.co/k69r5KGy/Present-simple.png',
  exercises: [
    { question: "She ___ to school every day. (go)", answer: "goes", options: ["go", "goes", "going", "gone"] },
    { question: "They ___ lunch at noon. (have)", answer: "have", options: ["has", "had", "have", "haves"] },
    { question: "My dad ___ coffee in the morning. (drink)", answer: "drinks", options: ["drinks", "drank", "drink", "drinking"] },
    { question: "I ___ in a small apartment. (live)", answer: "live", options: ["lives", "live", "living", "lived"] },
    { question: "He ___ to music after dinner. (listen)", answer: "listens", options: ["listen", "listens", "listening", "listened"] },
    { question: "The sun ___ in the east. (rise)", answer: "rises", options: ["rise", "rises", "rising", "rose"] },
    { question: "Water ___ at 100 degrees Celsius. (boil)", answer: "boils", options: ["boil", "boils", "boiling", "boiled"] },
    { question: "My sister ___ French at university. (study)", answer: "studies", options: ["study", "studies", "studying", "studied"] },
    { question: "The dog ___ in the garden. (play)", answer: "plays", options: ["play", "plays", "playing", "played"] },
    { question: "We ___ dinner at 7 PM. (eat)", answer: "eat", options: ["eats", "eat", "eating", "ate"] },
    { question: "The train ___ at 9 AM. (arrive)", answer: "arrives", options: ["arrive", "arrives", "arriving", "arrived"] },
    { question: "Birds ___ in the sky. (fly)", answer: "fly", options: ["flys", "flies", "fly", "flying"] },
    { question: "She ___ English very well. (speak)", answer: "speaks", options: ["speak", "speaks", "speaking", "spoke"] },
    { question: "The shop ___ at 8 AM. (open)", answer: "opens", options: ["open", "opens", "opening", "opened"] },
    { question: "My friend ___ in London. (work)", answer: "works", options: ["work", "works", "working", "worked"] },
    { question: "The movie ___ at 8 PM. (start)", answer: "starts", options: ["start", "starts", "starting", "started"] },
    { question: "He ___ basketball every weekend. (play)", answer: "plays", options: ["play", "plays", "playing", "played"] },
    { question: "The children ___ their homework after school. (do)", answer: "do", options: ["does", "do", "doing", "did"] },
    { question: "She ___ breakfast at 7 AM. (make)", answer: "makes", options: ["make", "makes", "making", "made"] },
    { question: "The bus ___ every 30 minutes. (come)", answer: "comes", options: ["come", "comes", "coming", "came"] },
    { question: "They ___ in a big house. (live)", answer: "live", options: ["lives", "live", "living", "lived"] },
    { question: "The teacher ___ the lesson clearly. (explain)", answer: "explains", options: ["explain", "explains", "explaining", "explained"] },
    { question: "It ___ a lot in winter. (rain)", answer: "rains", options: ["rain", "rains", "raining", "rained"] },
    { question: "The library ___ at 9 PM. (close)", answer: "closes", options: ["close", "closes", "closing", "closed"] },
    { question: "My cat ___ milk every morning. (drink)", answer: "drinks", options: ["drink", "drinks", "drinking", "drank"] },
   { question: "They ___ (play) football.", answer: "play", options: ["play", "plays", "playing", "played"] },
  { question: "She ___ (read) a book.", answer: "reads", options: ["reads", "read", "reading", "readed"] },
  { question: "I ___ (watch) TV.", answer: "watch", options: ["watch", "watches", "watching", "watched"] },
  { question: "We ___ (eat) lunch.", answer: "eat", options: ["eat", "eats", "eating", "ate"] },
  { question: "He ___ (write) a letter.", answer: "writes", options: ["writes", "write", "writing", "writed"] },
  { question: "They ___ (run) in the park.", answer: "run", options: ["run", "runs", "running", "ran"] },
  { question: "She ___ (draw) a picture.", answer: "draws", options: ["draws", "draw", "drawing", "drawed"] },
  { question: "I ___ (play) the guitar.", answer: "play", options: ["play", "plays", "playing", "played"] },
  { question: "We ___ (sing) a song.", answer: "sing", options: ["sing", "sings", "singing", "sang"] },
  { question: "He ___ (cook) dinner.", answer: "cooks", options: ["cooks", "cook", "cooking", "cooked"] },
  { question: "They ___ (dance) together.", answer: "dance", options: ["dance", "dances", "dancing", "danced"] },
  { question: "She ___ (swim) in the pool.", answer: "swims", options: ["swims", "swim", "swimming", "swam"] },
  { question: "I ___ (write) in my notebook.", answer: "write", options: ["write", "writes", "writing", "writed"] },
  { question: "We ___ (listen) to music.", answer: "listen", options: ["listen", "listens", "listening", "listened"] },
  { question: "He ___ (clean) his room.", answer: "cleans", options: ["cleans", "clean", "cleaning", "cleaned"] },
  ]
};

export default PresentSimpleGrammar;