const PresentPerfectGrammar = {
  id: '6',
  title: 'Present Perfect',
  description: 'Learn how to use the present perfect tense',
  imageUrl: 'https://i.ibb.co/VpWkK1R1/Present-perfect-1.png',
  exercises: [
    { question: "I ___ ___ to Paris. (never/be)", answer: "have never been", options: ["has never been", "have never been", "had never been", "am never been"] },
    { question: "She ___ already ___ her homework. (finish)", answer: "has finished", options: ["have finished", "has finished", "had finished", "is finished"] },
    { question: "They ___ ___ three tests this week. (take)", answer: "have taken", options: ["has taken", "have taken", "had taken", "are taken"] },
    { question: "He ___ just ___ lunch. (eat)", answer: "has eaten", options: ["have eaten", "has eaten", "had eaten", "is eaten"] },
    { question: "We ___ ___ here since 2010. (live)", answer: "have lived", options: ["has lived", "have lived", "had lived", "are lived"] },
    { question: "The train ___ already ___ . (leave)", answer: "has left", options: ["have left", "has left", "had left", "is left"] },
    { question: "___ you ever ___ to Japan? (be)", answer: "Have been", options: ["Has been", "Have been", "Had been", "Are been"] },
    { question: "They ___ not ___ the movie yet. (see)", answer: "have seen", options: ["has seen", "have seen", "had seen", "are seen"] },
    { question: "I ___ ___ my keys. (lose)", answer: "have lost", options: ["has lost", "have lost", "had lost", "am lost"] },
    { question: "She ___ ___ three books this week. (read)", answer: "has read", options: ["has read", "have read", "had read", "is read"] },
    { question: "We ___ ___ our lunch. (finish)", answer: "have finished", options: ["has finished", "have finished", "had finished", "are finished"] },
    { question: "The students ___ ___ their exams. (complete)", answer: "have completed", options: ["has completed", "have completed", "had completed", "are completed"] },
    { question: "He ___ just ___ home. (arrive)", answer: "has arrived", options: ["have arrived", "has arrived", "had arrived", "is arrived"] },
    { question: "I ___ never ___ sushi. (eat)", answer: "have eaten", options: ["has eaten", "have eaten", "had eaten", "am eaten"] },
    { question: "They ___ ___ the room. (clean)", answer: "have cleaned", options: ["has cleaned", "have cleaned", "had cleaned", "are cleaned"] },
    { question: "___ you ___ the news? (hear)", answer: "Have heard", options: ["Has heard", "Have heard", "Had heard", "Are heard"] },
    { question: "She ___ ___ all her money. (spend)", answer: "has spent", options: ["has spent", "have spent", "had spent", "is spent"] },
    { question: "We ___ ___ to many countries. (travel)", answer: "have traveled", options: ["has traveled", "have traveled", "had traveled", "are traveled"] },
    { question: "The dog ___ ___ its food. (eat)", answer: "has eaten", options: ["has eaten", "have eaten", "had eaten", "is eaten"] },
    { question: "I ___ already ___ my work. (finish)", answer: "have finished", options: ["has finished", "have finished", "had finished", "am finished"] },
    { question: "They ___ ___ the house. (paint)", answer: "have painted", options: ["has painted", "have painted", "had painted", "are painted"] },
    { question: "He ___ ___ English for five years. (study)", answer: "has studied", options: ["has studied", "have studied", "had studied", "is studied"] },
    { question: "We ___ never ___ a lion. (see)", answer: "have seen", options: ["has seen", "have seen", "had seen", "are seen"] },
    { question: "She ___ just ___ the door. (close)", answer: "has closed", options: ["has closed", "have closed", "had closed", "is closed"] },
    { question: "I ___ ___ my best friend since morning. (not/see)", answer: "have not seen", options: ["has not seen", "have not seen", "had not seen", "am not seen"] },
    { question: "They ___ (not finish) their work yet.", answer: "haven't finished", options: ["haven't finished", "didn't finish", "not finished", "hasn't finished"] },
  { question: "She ___ (not be) to Paris.", answer: "hasn't been", options: ["hasn't been", "didn't be", "not been", "haven't been"] },
  { question: "I ___ (not see) that movie.", answer: "haven't seen", options: ["haven't seen", "didn't see", "not seen", "hasn't seen"] },
  { question: "We ___ (not eat) lunch.", answer: "haven't eaten", options: ["haven't eaten", "didn't eat", "not eaten", "hasn't eaten"] },
  { question: "She ___ (not visit) London.", answer: "hasn't visited", options: ["hasn't visited", "didn't visit", "not visited", "haven't visited"] },
  { question: "They ___ (not start) the project.", answer: "haven't started", options: ["haven't started", "didn't start", "not started", "hasn't started"] },
  { question: "He ___ (not finish) his homework.", answer: "hasn't finished", options: ["hasn't finished", "didn't finish", "not finished", "haven't finished"] },
  { question: "We ___ (not meet) before.", answer: "haven't met", options: ["haven't met", "didn't meet", "not met", "hasn't met"] },
  { question: "I ___ (not hear) the news.", answer: "haven't heard", options: ["haven't heard", "didn't hear", "not heard", "hasn't heard"] },
  { question: "He ___ (not call) you.", answer: "hasn't called", options: ["hasn't called", "didn't call", "not called", "haven't called"] },
  { question: "She ___ (not try) sushi before.", answer: "hasn't tried", options: ["hasn't tried", "didn't try", "not tried", "haven't tried"] },
  { question: "You ___ (not finish) reading that book.", answer: "haven't finished", options: ["haven't finished", "didn't finish", "not finished", "hasn't finished"] },
  { question: "They ___ (not arrive) yet.", answer: "haven't arrived", options: ["haven't arrived", "didn't arrive", "not arrived", "hasn't arrived"] },
  { question: "She ___ (not complete) the course.", answer: "hasn't completed", options: ["hasn't completed", "didn't complete", "not completed", "haven't completed"] },
  { question: "We ___ (not decide) yet.", answer: "haven't decided", options: ["haven't decided", "didn't decide", "not decided", "hasn't decided"] },
  { question: "They ___ (not finish) the assignment.", answer: "haven't finished", options: ["haven't finished", "didn't finish", "not finished", "hasn't finished"] },
  { question: "I ___ (not eat) breakfast.", answer: "haven't eaten", options: ["haven't eaten", "didn't eat", "not eaten", "hasn't eaten"] },
  { question: "You ___ (not see) that film.", answer: "haven't seen", options: ["haven't seen", "didn't see", "not seen", "hasn't seen"] },
  { question: "He ___ (not sleep) well.", answer: "hasn't slept", options: ["hasn't slept", "didn't sleep", "not slept", "haven't slept"] },
  { question: "We ___ (not discuss) this before.", answer: "haven't discussed", options: ["haven't discussed", "didn't discuss", "not discussed", "hasn't discussed"] },
  { question: "She ___ (not read) the article.", answer: "hasn't read", options: ["hasn't read", "didn't read", "not read", "haven't read"] },
  { question: "They ___ (not meet) him before.", answer: "haven't met", options: ["haven't met", "didn't meet", "not met", "hasn't met"] },
  { question: "They ___ (not start) class.", answer: "haven't started", options: ["haven't started", "didn't start", "not started", "hasn't started"] },
  { question: "She ___ (not try) this dish.", answer: "hasn't tried", options: ["hasn't tried", "didn't try", "not tried", "haven't tried"] },
  { question: "We ___ (not receive) mail.", answer: "haven't received", options: ["haven't received", "didn't receive", "not received", "hasn't received"] }

 
  ]
};

export default PresentPerfectGrammar;