const PreteritGrammar = {
  id: '3',
  title: 'Prétérit',
  description: 'Learn how to use the past simple tense',
  imageUrl: 'https://i.ibb.co/JjRHKjP7/Pr-t-rit.png',
  exercises: [
    { question: "Yesterday, I ___ to the park. (go)", answer: "went", options: ["go", "gone", "went", "going"] },
    { question: "She ___ her lunch at noon. (eat)", answer: "ate", options: ["eat", "ate", "eaten", "eating"] },
    { question: "They ___ football last weekend. (play)", answer: "played", options: ["play", "played", "playing", "plays"] },
    { question: "He ___ the movie last night. (watch)", answer: "watched", options: ["watch", "watched", "watching", "watches"] },
    { question: "We ___ in Paris last summer. (live)", answer: "lived", options: ["live", "lived", "living", "lives"] },
    { question: "Last week, she ___ a new car. (buy)", answer: "bought", options: ["buy", "bought", "buyed", "buying"] },
    { question: "The children ___ in the garden yesterday. (play)", answer: "played", options: ["play", "played", "playing", "plays"] },
    { question: "I ___ my grandmother last month. (visit)", answer: "visited", options: ["visit", "visited", "visiting", "visits"] },
    { question: "They ___ to London last year. (fly)", answer: "flew", options: ["fly", "flew", "flown", "flying"] },
    { question: "He ___ English at school. (study)", answer: "studied", options: ["study", "studied", "studying", "studies"] },
    { question: "We ___ to the beach last summer. (go)", answer: "went", options: ["go", "went", "gone", "going"] },
    { question: "She ___ a beautiful dress yesterday. (wear)", answer: "wore", options: ["wear", "wore", "worn", "wearing"] },
    { question: "I ___ my friend at the party. (meet)", answer: "met", options: ["meet", "met", "meeting", "meets"] },
    { question: "They ___ a great time at the concert. (have)", answer: "had", options: ["have", "had", "having", "has"] },
    { question: "He ___ the book in one day. (read)", answer: "read", options: ["read", "reads", "reading", "readed"] },
    { question: "The dog ___ all day. (sleep)", answer: "slept", options: ["sleep", "slept", "sleeping", "sleeps"] },
    { question: "We ___ a great time at the party. (have)", answer: "had", options: ["have", "had", "having", "has"] },
    { question: "She ___ her keys this morning. (lose)", answer: "lost", options: ["lose", "lost", "losing", "loses"] },
    { question: "The teacher ___ us a story. (tell)", answer: "told", options: ["tell", "told", "telling", "tells"] },
    { question: "I ___ my homework last night. (do)", answer: "did", options: ["do", "did", "doing", "does"] },
    { question: "They ___ late to class. (arrive)", answer: "arrived", options: ["arrive", "arrived", "arriving", "arrives"] },
    { question: "He ___ his bike yesterday. (ride)", answer: "rode", options: ["ride", "rode", "ridden", "riding"] },
    { question: "We ___ dinner at 7pm. (eat)", answer: "ate", options: ["eat", "ate", "eaten", "eating"] },
    { question: "She ___ her essay last week. (write)", answer: "wrote", options: ["write", "wrote", "written", "writing"] },
    { question: "They ___ to music all night. (listen)", answer: "listened", options: ["listen", "listened", "listening", "listens"] },
    { question: "Yesterday, I ___ at home. (be)", answer: "was", options: ["is", "was", "are", "were"] },
    { question: "Last week, they ___ at school. (be)", answer: "were", options: ["is", "was", "are", "were"] },
    { question: "She ___ happy yesterday. (be)", answer: "was", options: ["is", "was", "are", "were"] },
    { question: "We ___ late for class. (be)", answer: "were", options: ["is", "was", "are", "were"] },
    { question: "He ___ my friend last year. (be)", answer: "was", options: ["is", "was", "are", "were"] },
    { question: "The dogs ___ noisy last night. (be)", answer: "were", options: ["is", "was", "are", "were"] },
    { question: "It ___ cold yesterday. (be)", answer: "was", options: ["is", "was", "are", "were"] },
    { question: "You ___ at the party. (be)", answer: "were", options: ["is", "was", "are", "were"] },
    { question: "The shop ___ closed yesterday. (be)", answer: "was", options: ["is", "was", "are", "were"] },
    { question: "My parents ___ tired last night. (be)", answer: "were", options: ["is", "was", "are", "were"] }
  ]
};

export default PreteritGrammar;