const OpinionLevel2Vocab = {
  id: '209',
  title: 'Opinion +',
  description: 'Expand your ability to express opinions with linking phrases and justifications',
  imageUrl: 'https://i.ibb.co/jNHrhBy/Opinion-Level-2.webp',
  thumbnail: require('../../assets/thumbnails/opinion-level-2-thumbnail.png'),
  flashcards: [
    { english: 'Perfect', french: 'Parfait' },
    { english: 'Ideal', french: 'Idéal' },
    { english: 'Amazing', french: 'Incroyable' },
    { english: 'Fantastic', french: 'Fantastique' },
    { english: 'Breathtaking', french: 'À couper le souffle' },
    { english: 'Great', french: 'Génial' },
    { english: 'Extraordinary', french: 'Extraordinaire' },
    { english: 'Awesome', french: 'Génial' },
    { english: 'Nice', french: 'Sympa' },
    { english: 'Pleasant', french: 'Agréable' },
    { english: 'Interesting', french: 'Intéressant' },
    { english: 'Clever', french: 'Malin' },
    { english: 'Beautiful', french: 'Beau / Belle' },
    { english: 'Charming', french: 'Charmant' },
    { english: 'Cool', french: 'Cool' },
    { english: 'Fun', french: 'Amusant' },
    { english: 'Entertaining', french: 'Divertissant' },
    { english: 'Funny', french: 'Drôle' },
    { english: 'Hilarious', french: 'Hilarant' },
    { english: 'Famous', french: 'Célèbre' },
    { english: 'Delicious', french: 'Délicieux' },
    { english: 'Surprising', french: 'Surprenant' },
    { english: 'Scary', french: 'Effrayant' },
    { english: 'Boring', french: 'Ennuyeux' },
    { english: 'Weird', french: 'Bizarre' },
    { english: 'Confusing', french: 'Déroutant' },
    { english: 'Awful', french: 'Horrible' },
    { english: 'Terrible', french: 'Terrible' },
    { english: 'Shocking', french: 'Choquant' },
    { english: 'Sad', french: 'Triste' },
    { english: 'Heartbreaking', french: 'Déchirant' },
    { english: 'Crazy', french: 'Fou' },
    { english: 'Silly', french: 'Bête' },
    { english: 'Embarrassing', french: 'Gênant' },
    { english: 'Awkward', french: 'Maladroit' },
    { english: 'Tiring', french: 'Fatigant' },
    { english: 'Exhausting', french: 'Épuisant' },
    { english: 'Stressful', french: 'Stressant' },
    { english: 'Disgusting', french: 'Dégoûtant' }
  ]
};

export default OpinionLevel2Vocab;