const SchoolLvl2Vocab = {
  id: '204',
  title: 'School life',
  imageUrl: 'https://i.ibb.co/Y4LmMVjP/School-lvl-2.webp',
  thumbnail: require('../../assets/thumbnails/school-life-thumbnail.png'),
  description: 'More advanced school vocabulary: subjects, classrooms and school activities',
  flashcards: [
  { "english": "A college", "french": "Une université" },
  { "english": "A high school", "french": "Un lycée" },
  { "english": "A middle school", "french": "Un collège" },
  { "english": "A student", "french": "Un élève / Une élève" },
  { "english": "A teacher", "french": "Un professeur / Une professeure" },
  { "english": "Classes", "french": "Cours" },
  { "english": "A schedule", "french": "Un emploi du temps" },
  { "english": "A classroom", "french": "Une salle de classe" },
  { "english": "Recess", "french": "Récréation" },
  { "english": "The bell", "french": "La sonnerie" },
  { "english": "A playground (UK)", "french": "Une cour de récréation" },
  { "english": "A schoolyard (US)", "french": "Une cour d'école" },
  { "english": "The cafeteria", "french": "La cafétéria" },
  { "english": "A library", "french": "Une bibliothèque" },
  { "english": "A gym", "french": "Un gymnase" },
  { "english": "The sports field", "french": "Le terrain de sport" },
  { "english": "An exam", "french": "Un examen" },
  { "english": "A locker", "french": "Un casier" },

  { "english": "Football", "french": "Football américain" },
  { "english": "Soccer", "french": "Football" },
  { "english": "Basketball", "french": "Basketball" },
  { "english": "Baseball", "french": "Baseball" },
  { "english": "Hockey", "french": "Hockey" },
  { "english": "Cheerleading", "french": "Pom-pom girls / Cheerleading" },
  { "english": "Drama", "french": "Théâtre" },
  { "english": "Spanish", "french": "Espagnol" },
  { "english": "Chess", "french": "Échecs" },
  { "english": "Film", "french": "Cinéma" },
  { "english": "Yearbook", "french": "Le livre de fin d'année" },
  { "english": "School newspaper", "french": "Journal scolaire" },
  { "english": "Mock trial", "french": "Faux procès" },
  { "english": "Debate club", "french": "Club de débat" },
  { "english": "Marching band", "french": "Fanfare" }
]
};

export default SchoolLvl2Vocab;
