const VideoGamePowersVocab = {
  id: '206',
  title: 'Video game powers',
  description: 'Powers and special abilities commonly found in video games',
  imageUrl: 'https://wretggbpaejzjdilemit.supabase.co/storage/v1/object/public/lesson-images/15274719ab/video-game-powers.webp',
  thumbnail: require('../../assets/thumbnails/video-game-actions-thumbnail.png'),
  flashcards: [
    { "english": "(to) run really fast", "french": "Courir très vite" },
    { "english": "(to) fly", "french": "Voler" },
    { "english": "(to) swim", "french": "Nager" },
    { "english": "(to) jump", "french": "Sauter" },
    { "english": "(to) teleport", "french": "Se téléporter" },
    { "english": "(to) punch", "french": "Donner un coup de poing" },
    { "english": "(to) kick", "french": "Donner un coup de pied" },
    { "english": "(to) use a sword", "french": "Utiliser une épée" },
    { "english": "(to) breathe fire", "french": "Cracher du feu" },
    { "english": "(to) shoot electricity", "french": "Projeter de l'électricité" },
    { "english": "(to) freeze", "french": "Geler" },
    { "english": "(to) use a force field", "french": "Utiliser un champ de force" },
    { "english": "(to) transform", "french": "Se transformer" },
    { "english": "(to) become invincible", "french": "Devenir invincible" },
    { "english": "(to) turn invisible", "french": "Devenir invisible" },
    { "english": "(to) build", "french": "Construire" },
    { "english": "(to) fix anything", "french": "Réparer n'importe quoi" },
    { "english": "(to) break anything", "french": "Casser n'importe quoi" },
    { "english": "(to) search", "french": "Chercher" },
    { "english": "(to) rewind time", "french": "Remonter le temps" },
    { "english": "(to) attack", "french": "Attaquer" },
    { "english": "(to) battle", "french": "Combattre" },
    { "english": "(to) defend", "french": "Défendre" },
    { "english": "(to) protect", "french": "Protéger" },
    { "english": "(to) work together", "french": "Travailler ensemble" },
    { "english": "(to) collaborate", "french": "Collaborer" },
    { "english": "(to) choose", "french": "Choisir" },
    { "english": "(to) select", "french": "Sélectionner" },
    { "english": "(to) level up", "french": "Monter de niveau" },
    { "english": "(to) save", "french": "Sauvegarder" },
    { "english": "(to) collect", "french": "Collecter" },
    { "english": "(to) explore", "french": "Explorer" },
    { "english": "(to) avoid", "french": "Éviter" },
    { "english": "(to) find", "french": "Trouver" }
  ]
};

export default VideoGamePowersVocab;
