const VideoGamePowersVocab = {
  id: '206',
  title: 'Video game powers',
  description: 'Powers and special abilities commonly found in video games',
  imageUrl: 'https://i.ibb.co/5XCFgjgq/Video-game-powers.webp',
  flashcards: [
    { "english": "(to) run really fast", "french": "courir très vite" },
    { "english": "(to) fly", "french": "voler" },
    { "english": "(to) swim", "french": "nager" },
    { "english": "(to) jump", "french": "sauter" },
    { "english": "(to) teleport", "french": "téléporter" },
    { "english": "(to) punch", "french": "donner un coup de poing" },
    { "english": "(to) kick", "french": "donner un coup de pied" },
    { "english": "(to) use a sword", "french": "utiliser une épée" },
    { "english": "(to) breathe fire", "french": "cracher du feu" },
    { "english": "(to) shoot electricity", "french": "projeter de l'électricité" },
    { "english": "(to) freeze", "french": "geler" },
    { "english": "(to) use a force field", "french": "utiliser un champ de force" },
    { "english": "(to) transform", "french": "se transformer" },
    { "english": "(to) become invincible", "french": "devenir invincible" },
    { "english": "(to) turn invisible", "french": "devenir invisible" },
    { "english": "(to) build", "french": "construire" },
    { "english": "(to) fix anything", "french": "réparer n'importe quoi" },
    { "english": "(to) break anything", "french": "casser n'importe quoi" },
    { "english": "(to) search", "french": "chercher" },
    { "english": "(to) rewind time", "french": "remonter le temps" },
    { "english": "(to) attack", "french": "attaquer" },
    { "english": "(to) battle", "french": "combattre" },
    { "english": "(to) defend", "french": "défendre" },
    { "english": "(to) protect", "french": "protéger" },
    { "english": "(to) work together", "french": "travailler ensemble" },
    { "english": "(to) collaborate", "french": "collaborer" },
    { "english": "(to) choose", "french": "choisir" },
    { "english": "(to) select", "french": "sélectionner" },
    { "english": "(to) level up", "french": "monter de niveau" },
    { "english": "(to) save", "french": "sauver" },
    { "english": "(to) collect", "french": "collectionner" },
    { "english": "(to) explore", "french": "explorer" },
    { "english": "(to) avoid", "french": "éviter" },
    { "english": "(to) find", "french": "trouver" }
  ]
};

export default VideoGamePowersVocab;