import { StyleSheet } from 'react-native';




export const adminSharedStyles = StyleSheet.create({
  statusCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 14,
  },
  statusHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  statusTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  statusTitle: {
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  statusSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  statusButtonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  publishLiveButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#15803D',
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  buildBundleButton: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#1671B6',
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  buildBundleButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  statusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statusMetric: {
    minWidth: 138,
    flex: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statusMetricValue: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 22,
  },
  statusMetricLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: 1,
  },
  adminTabBar: {
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 6,
  },
  adminTabButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
  },
  adminTabText: {
    fontSize: 14,
    fontWeight: '900',
  },
  editorCard: {
    marginHorizontal: 16,
    marginBottom: 22,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 14,
  },
  chapterLinksTitleBlock: {
    flex: 1,
  },
  chapterLinksSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginTop: -6,
  },
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#CFE2F5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  exportButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1671B6',
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 12,
  },
  field: {
    marginBottom: 14,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  input: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    fontSize: 15,
    fontWeight: '600',
  },
  secondaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: '#EEF3F8',
  },
  disabledSecondaryButton: {
    opacity: 0.45,
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#44505C',
  },
  primaryButton: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: '#1671B6',
  },
  primaryButtonAttention: {
    backgroundColor: '#0F5E98',
  },
  disabledButton: {
    opacity: 0.45,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#fff',
  },
  deleteLessonButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#FFF1F1',
  },
  deleteLessonButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#C62828',
  },
});
